### ISSUE TITLE
Pinning the plugin version doesn't pin the linter version

### ISSUE THREAD

**Issue by tessereth** [buildkite-plugins/plugin-linter-buildkite-plugin#2] opened 2018-04-30 23:46 UTC
While you can pin the version of the plugin in `pipeline.yml`, the plugin just pulls the latest version of the `plugin-linter` docker image. This can cause builds to fail under your feet if something changes in https://github.com/buildkite-plugins/buildkite-plugin-linter.

**Comment by tessereth** [comment] 2018-05-01 01:03
The linter now requires a plugin example in the README. That possibly came in when you changed to TAP output, I didn't look that far. But it used to just log and continue if it didn't find one. I can see an argument for requiring it, but I'm just the special snowflake that it doesn't work for.

**Comment by toolmantim** [comment] 2018-05-01 01:30
Thanks for being patient zero for these problems! It looks like you have an example in the README though?

```yml
  - label: annotate
    plugins:
      bugcrowd/test-summary#v1.1.0:
        inputs:
          - label: rspec
            artifact_path: artifacts/rspec*
            type: junit
          - label: ava
            artifact_path: artifacts/ava.tap
            type: tap
          - label: rubocop
            artifact_path: artifacts/rubocop.txt
            type: oneline
        formatter:
          type: details
        context: test-summary
```

Would you mind opening an issue on https://github.com/buildkite/buildkite-plugin-linter and I'll get that fixed for you?

**Comment by tessereth** [comment] 2018-05-01 02:01
Eh, debugging is fun. At least it's all open source so I can find out what's actually going on. Issue filed: https://github.com/buildkite-plugins/buildkite-plugin-linter/issues/10

**Comment by toolmantim** [comment] 2018-05-03 04:14
I'm going to close this, as for now it's expected behaviour. But if it causes more heartache we can look at pinning it instead.

**Closed** 2018-05-03 04:14 UTC

**Comment by tessereth** [comment] 2018-11-08 23:37
Hey, so this happened to me again due to https://github.com/buildkite-plugins/buildkite-plugin-linter/pull/155. Perhaps at the very least you could add a changelog so I don't have to look through commit history to figure out why something breaks?
